### ISSUE TITLE
Status for Scala 2.11 and Beyond...

### ISSUE THREAD

**Issue by godenji** [ps-mr/LinqOnSteroids#3]
Stumbled upon this project while searching for developers still using ScalaQuery (instead of Slick).

What's the status moving forward, for research only, or is there potential for a LINQ-esque production alternative to Slick, Squeryl, et al?

You guys might be interested in a paper on a Haskell version of LINQ recently published by Philip Wadler and colleagues at the University of Edinburgh:
http://homepages.inf.ed.ac.uk/slindley/papers/practical-theory-of-linq.pdf

as well as a presentation of their research in action:
http://www.infoq.com/presentations/theory-language-integrated-query

Really interesting material. The Scala community is, IMO, ahead of Haskell in terms of close-to-LINQ production libraries, ScalaQuery being the closest that I have seen to date (Slick's switch to Scala collections groupBy/sortBy and tuple syntax makes extra boilerplate and a far uglier DSL).

**Comment by Blaisorblade** [comment]
Closing as stale — I've also just clarified the project status on the repo README.
